# Base configs
baseurl: ""
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: "UA-46465113-2"

# UI configs
title: "Roketpik Photo"
subtitle: "See the world through my eyes!"
author: "Artur Shamsutdinov"
header:
 title: "Roketpik"
 subtitle: "by Artur Shamsutdinov"
footer:
 name: "Hey there, my name is Artur"
 bio: "I am a developer and photographer. Love making photos of everyday life and some portraits."
 github: ""
web_design: "AJ"
social_urls:
  instagram: "https://www.instagram.com/roketpik"
  github: "https://www.github.com/roketstorm"
